report_content = """
<html>
<head>
  <title>Sample Report</title>
</head>
<body>
  <h1>Generated Report</h1>
  <p>This is a report generated by the script.</p>
</body>
</html>
"""

# Write the report content to the report.html file
report_filename = "report.html"
with open(report_filename, "w") as report_file:
    report_file.write(report_content)

# After generating the report, you can copy it to a directory for uploading as an artifact
import shutil
shutil.copy(report_filename, "pr/report")

