



name: PR-Checks

on:
  push:
    branches:
      - feature

jobs:
  databricks_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Junit tests
        run: |
          pip install pytest
          pytest tests/
          pytest --junitxml=junit/test-report.xml

      - name: Upload Junit test report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: junit-test-report
          path: junit

      - name: security_scan
        run: |
          pip install bandit
          # bandit -r notebooks/ && pytest tests/
         
          pip install pytest
          bandit -r notebooks/
          pytest tests/ --junitxml=junit/security-scan.xml

      - name: Upload security scan report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: security-scan-report
          path: junit/security-scan.xml

  # create_pull_request:
  #   runs-on: ubuntu-latest
  #   needs: databricks_checks
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Create pull request
  #       uses: peter-evans/create-pull-request@v3
  #       with:
  #         token: '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'
  #         branch: Release
  #         title: Automated PR:Security Scan
  #         body: |
  #           This pull request is automatically generated to trigger security scanning.
  #           Please review and merge if the checks pass.

  attach_reports:
    runs-on: ubuntu-latest
    # needs: create_pull_request
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download security scan report
        uses: actions/download-artifact@v2
        with:
          name: security-scan-report
          path: junit/security-scan.xml

      - name: Attach security scan report to pull request
        uses: actions/upload-artifact@v3.1.2
        with:
          name: attached-reports
          path: security-scan
