name: Copy Changes to Dev

on:
  push:
    branches:
      - Release

jobs:
  copy-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v2
        with:
          ref: Release

      - name: Create new dev branch
        run: |
          git checkout -b dev
          git push origin dev






# name: Copy To dev Branches
# on:
#   push:
#     branches:
#       - Release
# #testrun
# jobs:
#   copy-commit:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 2

#       - name: Copy Commit
#         uses: jeffreyc/copy-commit-to-another-repo@v1.0.0
#         env:
#           PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT_TOKEN }}
#         with:
#           # include: 'hello,world?'
#           # exclude: '"world,"'
#           destination: 'msakare/databricks'
#           branch: 'dev'

      # - name: Copy Commit
      #   uses: jeffreyc/copy-commit-to-another-repo@v1.0.0
      #   env:
      #     PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT_TOKEN }}
      #   with:
      #     # include: 'hello,world?'
      #     # exclude: '"world,"'
      #     destination: 'msakare/databricks'
      #     branch: 'test_repo'





