name: Copy To dev Branches
on:
  push:
    branches:
      - Release
#testrun
jobs:
  copy-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      # - name: Copy Commit
      #   uses: jeffreyc/copy-commit-to-another-repo@v1.0.0
      #   env:
      #     PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT_TOKEN }}
      #   with:
      #     # include: 'hello,world?'
      #     # exclude: '"world,"'
      #     destination: 'msakare/databricks'
      #     branch: 'development'

      - name: Copy Commit
        uses: jeffreyc/copy-commit-to-another-repo@v1.0.0
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          # include: 'hello,world?'
          # exclude: '"world,"'
          destination: 'msakare/databricks'
          branch: 'dev_repo'



