# name: Copy To Branches
# on:
#   push:
#     branches:
#       - Release
# #testrun
# jobs:
#   copy-commit:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 2
#       - name: Copy Commit
#         uses: jeffreyc/copy-commit-to-another-repo@v1.0.0
#         env:
#           PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT_TOKEN }}
#         with:
#           # include: 'hello,world?'
#           # exclude: '"world,"'
#           destination: 'msakare/databricks'
#           branch: 'development'

#       - name: Copy Commit
#         uses: jeffreyc/copy-commit-to-another-repo@v1.0.0
#         env:
#           PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT_TOKEN }}
#         with:
#           # include: 'hello,world?'
#           # exclude: '"world,"'
#           destination: 'msakare/databricks'
#           branch: 'test_repo'


name: Copy To Branches
on:
  push:
    branches:
      - Release

jobs:
  copy-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          ref: Release  # Specify the branch to copy from
          repository: msakare/databricks  # Specify the source repository

      - name: Clone destination repositories
        run: |
          git clone https://github.com/msakare/development.git
          git clone https://github.com/msakare/test_repo.git

      - name: Apply changes and push to development
        run: |
          cd development
          git checkout development
          cp -r ../databricks/* .  # Copy the changes from source repository
          git add .
          git commit -m "Copy changes from Release"
          git push origin development

      - name: Apply changes and push to test_repo
        run: |
          cd ../test_repo
          git checkout test_repo
          cp -r ../databricks/* .  # Copy the changes from source repository
          git add .
          git commit -m "Copy changes from Release"
          git push origin test_repo


