name: Copy To Branches

on:
  push:
    branches:
      - Release

jobs:
  copy-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          ref: Release  # Specify the branch to copy from
          path: source  # Specify a path to copy changes from

      - name: Apply changes to development
        run: |
          cp -r source/. .
          git add .
          git commit -m "Merge changes from Release into development"
          git push origin development

      - name: Apply changes to test_repo
        run: |
          cp -r source/. .
          git add .
          git commit -m "Merge changes from Release into test_repo"
          git push origin test_repo




# name: Copy To dev Branches
# on:
#   push:
#     branches:
#       - Release
# #testrun
# jobs:
#   copy-commit:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 2

#       - name: Copy Commit
#         uses: jeffreyc/copy-commit-to-another-repo@v1.0.0
#         env:
#           PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT_TOKEN }}
#         with:
#           # include: 'hello,world?'
#           # exclude: '"world,"'
#           destination: 'msakare/databricks'
#           branch: 'dev'

      # - name: Copy Commit
      #   uses: jeffreyc/copy-commit-to-another-repo@v1.0.0
      #   env:
      #     PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT_TOKEN }}
      #   with:
      #     # include: 'hello,world?'
      #     # exclude: '"world,"'
      #     destination: 'msakare/databricks'
      #     branch: 'test_repo'





