name: Merge to Development

on:
  push:
    branches:
      - Release

jobs:
  merge_to_development:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Release into Development
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Ensure the development branch is up-to-date
          git fetch origin development

          # Merge Release into Development
          git checkout development
          git merge origin/Release --no-ff --no-commit --allow-unrelated-histories
          git commit -m "Merge Release into Development" --allow-empty
          git push origin development

          # Switch back to the original branch
          git checkout ${{ github.ref }}










# name: Copy To dev Branches
# on:
#   push:
#     branches:
#       - Release
# #testrun
# jobs:
#   copy-commit:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 2

#       - name: Copy Commit
#         uses: jeffreyc/copy-commit-to-another-repo@v1.0.0
#         env:
#           PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT_TOKEN }}
#         with:
#           # include: 'hello,world?'
#           # exclude: '"world,"'
#           destination: 'msakare/databricks'
#           branch: 'dev'

      # - name: Copy Commit
      #   uses: jeffreyc/copy-commit-to-another-repo@v1.0.0
      #   env:
      #     PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT_TOKEN }}
      #   with:
      #     # include: 'hello,world?'
      #     # exclude: '"world,"'
      #     destination: 'msakare/databricks'
      #     branch: 'test_repo'





