name: PR Checks

on:
  push:
    branches:
      - feature

jobs:
  databricks_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Junit tests
        run: |
          pip install pytest
          pytest tests/
          pytest --junitxml=junit/test-report.xml

      - name: Upload Junit test report
        uses: actions/upload-artifacts
        with:
          name: junit-test-report
          path: junit

      - name: security_scan
        run: |
          pip install bandit
          bandit -r notebooks/ && pytest tests/  --output-path=security-scan

      - name: security_scan
        uses: actions/upload-artifact@v2
        with:
          name: security_scan
          path: security-scan

  create_pull_request:
    runs-on: ubuntu-latest
    needs: databricks_checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: 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
          branch: feature
          title: Automated PR:Security Scan
          body: |
            This pull request is automatically generated to trigger security scanning.
            Please review and merge if the checks pass.

  attach_reports:
    runs-on: ubuntu-latest
    needs: create_pull_request
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download security scan report
        uses: actions/download-artifact@v2
        with:
          name: security-scan-report
          path: security-scan

      - name: Attach security scan report to pull request
        uses: actions/upload-artifact@v2
        with:
          name: attached-reports
          path: security-scan

    # - name: Generate and Upload Artifacts
    #   id: generate_reports
    #   run: |
    #     # python generate_report.py
    #     #upload reports as artifacts
    #     echo "Security scan results" > report.txt
    #     bandit -r notebooks/ >> report.txt
    #     echo "Test results:" >> report.txt
    #     pytest tests/ >> report.txt

    # - name: Upload report artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: reports
    #     path: report.txt

    # - name: Generate reports
    #   run: |
    #     # Generate your reports here
    #     python generate_report.py

    # - name: Upload reports as PR comment
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: reports
    #     path: pr/

    # - name: Comment on PR with report link
    #   uses: actions/github-script@v4
    #   with:
    #     github-token: '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'
    #     script: |
    #       const fs = require('fs');
    #       const reportLink = fs.readFileSync('pr/report/report.html', 'utf8');
    #       github.issues.createComment({
    #         issue_number: context.issue.number,
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         body: `Test and security scan reports: ${reportLink}`
    #       });
