name: PR Checks

on:
  push:
    branches:
      - feature

jobs:
  databricks_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyGithub

      - name: Run Junit tests
        run: |
          pip install pytest
          pytest tests/
          pytest --junitxml=junit/test-report.xml

      - name: Upload Junit test report
        uses: actions/upload-artifact@v2
        with:
          name: junit-test-report
          path: junit/test-report.xml

      - name: Run security scan
        run: |
          pip install bandit
          bandit -r notebooks/ && pytest tests/ --junitxml=junit/security-scan-report.xml

      - name: Upload security scan results
        uses: actions/upload-artifact@v2
        with:
          name: security-scan-report
          path: junit/security-scan-report

  create_pull_request:
    runs-on: ubuntu-latest
    needs: databricks_checks
    steps:
      - uses: actions/checkout@v3

      # Make changes to pull request here


    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v3
    #   with:
    #     token: ${{ secrets.PAT_TOKEN }}
    #     branch: Release
    #     title: Automated PR: SecurityScan
    #     body: |
    #       This pull request is automatically generated to trigger security scanning.
    #       Please review and merge if the checks pass.
    #     reviewers: pankajadas, yashuonfire
          # Create the pull request using GitHub API
      - name: Create Pull Request comment
        run: |
          python create_pull_request.py ${{ secrets.PAT_TOKEN }} ${{ github.event.pull_request.number }} ${{ steps.databricks_checks.outputs.junit-report }} ${{ steps.databricks_checks.outputs.security-scan-report }}
          env:
          JUNIT_REPORT: ${{ steps.databricks_checks.outputs.junit-report }}
          SECURITY_SCAN_REPORT: ${{ steps.databricks_checks.outputs.security-scan-report }}

  attach_reports:
    runs-on: ubuntu-latest
    needs: create_pull_request
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download security scan report
        uses: actions/download-artifact@v2
        with:
          name: security-scan
          path: security-scan

      - name: Attach security scan report to pull request
        uses: actions/upload-artifact@v2
        with:
          name: attached-reports
          path: security-scan



    # - name: Generate and Upload Artifacts
    #   id: generate_reports
    #   run: |
    #     # python generate_report.py
    #     #upload reports as artifacts
    #     echo "Security scan results" > report.txt
    #     bandit -r notebooks/ >> report.txt
    #     echo "Test results:" >> report.txt
    #     pytest tests/ >> report.txt

    # - name: Upload report artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: reports
    #     path: report.txt

    # - name: Generate reports
    #   run: |
    #     # Generate your reports here
    #     python generate_report.py

    # - name: Upload reports as PR comment
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: reports
    #     path: pr/

    # - name: Comment on PR with report link
    #   uses: actions/github-script@v4
    #   with:
    #     github-token: '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'
    #     script: |
    #       const fs = require('fs');
    #       const reportLink = fs.readFileSync('pr/report/report.html', 'utf8');
    #       github.issues.createComment({
    #         issue_number: context.issue.number,
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         body: `Test and security scan reports: ${reportLink}`
    #       });
