name: PR Checks

on:
  push:
    branches:
      - feature

jobs:
  databricks_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyGithub

      # Run JUnit tests and security scan
      - name: Run tests and scan
        run: |
          pip install pytest
          pip install bandit
          pytest tests/
          pytest --junitxml=junit/test-report.xml
          bandit -r notebooks/
          pytest tests/ --junitxml=junit/security-scan-report.xml
          
      - name: Upload test and scan reports
        uses: actions/upload-artifact@v2
        with:
          name: junit-and-security-scan-reports
          path: junit,security-scan

      - name: Create Pull Request
        run: python create_pull_request.py ${{ secrets.PAT_TOKEN }}

  attach_reports:
    runs-on: ubuntu-latest
    needs: databricks_checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download test and scan reports
        uses: actions/download-artifact@v2
        with:
          name: junit-and-security-scan-reports
          path: reports

      - name: Attach reports to pull request
        run: python attach_reports.py ${{ secrets.PAT_TOKEN }}

      # Make changes to pull request here


    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v3
    #   with:
    #     token: ${{ secrets.PAT_TOKEN }}
    #     branch: Release
    #     title: Automated PR: SecurityScan
    #     body: |
    #       This pull request is automatically generated to trigger security scanning.
    #       Please review and merge if the checks pass.
    #     reviewers: pankajadas, yashuonfire
          # Create the pull request using GitHub API





    # - name: Generate and Upload Artifacts
    #   id: generate_reports
    #   run: |
    #     # python generate_report.py
    #     #upload reports as artifacts
    #     echo "Security scan results" > report.txt
    #     bandit -r notebooks/ >> report.txt
    #     echo "Test results:" >> report.txt
    #     pytest tests/ >> report.txt

    # - name: Upload report artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: reports
    #     path: report.txt

    # - name: Generate reports
    #   run: |
    #     # Generate your reports here
    #     python generate_report.py

    # - name: Upload reports as PR comment
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: reports
    #     path: pr/

    # - name: Comment on PR with report link
    #   uses: actions/github-script@v4
    #   with:
    #     github-token: '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'
    #     script: |
    #       const fs = require('fs');
    #       const reportLink = fs.readFileSync('pr/report/report.html', 'utf8');
    #       github.issues.createComment({
    #         issue_number: context.issue.number,
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         body: `Test and security scan reports: ${reportLink}`
    #       });
